@extends('layouts.app-assets')

@section('content')
    @include('components.home-slider')
    @include('components.home-services')
    @include('components.about-us')
    @include('components.home-parallax')
    @include('components.home-teachers-sec')
    @include('components.home-courses-sec')
    @include('components.home-experience')
    @include('components.parents-reviews')
    @include('components.request-us')
    @include('components.resents-blog')
    @include('components.footer-gallery')
@endsection
